package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Actividad generated by hbm2java
 */
public class Actividad  implements java.io.Serializable {


     private int codActividad;
     private Investigacion investigacion;
     private String nomActividad;
     private String descActividad;
     private Set bitacoraLabs = new HashSet(0);

    public Actividad() {
    }

	
    public Actividad(int codActividad) {
        this.codActividad = codActividad;
    }
    public Actividad(int codActividad, Investigacion investigacion, String nomActividad, String descActividad, Set bitacoraLabs) {
       this.codActividad = codActividad;
       this.investigacion = investigacion;
       this.nomActividad = nomActividad;
       this.descActividad = descActividad;
       this.bitacoraLabs = bitacoraLabs;
    }
   
    public int getCodActividad() {
        return this.codActividad;
    }
    
    public void setCodActividad(int codActividad) {
        this.codActividad = codActividad;
    }
    public Investigacion getInvestigacion() {
        return this.investigacion;
    }
    
    public void setInvestigacion(Investigacion investigacion) {
        this.investigacion = investigacion;
    }
    public String getNomActividad() {
        return this.nomActividad;
    }
    
    public void setNomActividad(String nomActividad) {
        this.nomActividad = nomActividad;
    }
    public String getDescActividad() {
        return this.descActividad;
    }
    
    public void setDescActividad(String descActividad) {
        this.descActividad = descActividad;
    }
    public Set getBitacoraLabs() {
        return this.bitacoraLabs;
    }
    
    public void setBitacoraLabs(Set bitacoraLabs) {
        this.bitacoraLabs = bitacoraLabs;
    }




}


