package sv.ues.dominio;
// Generated 01-24-2020 08:44:22 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Actividad01 generated by hbm2java
 */
public class Actividad01  implements java.io.Serializable {


     private int idActividad01;
     private ActividadEncabezado actividadEncabezado;
     private String identAnimal;
     private Integer tomaGlucemia30;
     private Integer tomaGlucemia60;
     private Integer tomaGlucemia120;
     private Integer tomaGlucemia180;
     private String promedio;
     private String usuario;
     private Date fechaRegistro;

    public Actividad01() {
    }

	
    public Actividad01(int idActividad01) {
        this.idActividad01 = idActividad01;
    }
    public Actividad01(int idActividad01, ActividadEncabezado actividadEncabezado, String identAnimal, Integer tomaGlucemia30, Integer tomaGlucemia60, Integer tomaGlucemia120, Integer tomaGlucemia180, String promedio, String usuario, Date fechaRegistro) {
       this.idActividad01 = idActividad01;
       this.actividadEncabezado = actividadEncabezado;
       this.identAnimal = identAnimal;
       this.tomaGlucemia30 = tomaGlucemia30;
       this.tomaGlucemia60 = tomaGlucemia60;
       this.tomaGlucemia120 = tomaGlucemia120;
       this.tomaGlucemia180 = tomaGlucemia180;
       this.promedio = promedio;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
    }
   
    public int getIdActividad01() {
        return this.idActividad01;
    }
    
    public void setIdActividad01(int idActividad01) {
        this.idActividad01 = idActividad01;
    }
    public ActividadEncabezado getActividadEncabezado() {
        return this.actividadEncabezado;
    }
    
    public void setActividadEncabezado(ActividadEncabezado actividadEncabezado) {
        this.actividadEncabezado = actividadEncabezado;
    }
    public String getIdentAnimal() {
        return this.identAnimal;
    }
    
    public void setIdentAnimal(String identAnimal) {
        this.identAnimal = identAnimal;
    }
    public Integer getTomaGlucemia30() {
        return this.tomaGlucemia30;
    }
    
    public void setTomaGlucemia30(Integer tomaGlucemia30) {
        this.tomaGlucemia30 = tomaGlucemia30;
    }
    public Integer getTomaGlucemia60() {
        return this.tomaGlucemia60;
    }
    
    public void setTomaGlucemia60(Integer tomaGlucemia60) {
        this.tomaGlucemia60 = tomaGlucemia60;
    }
    public Integer getTomaGlucemia120() {
        return this.tomaGlucemia120;
    }
    
    public void setTomaGlucemia120(Integer tomaGlucemia120) {
        this.tomaGlucemia120 = tomaGlucemia120;
    }
    public Integer getTomaGlucemia180() {
        return this.tomaGlucemia180;
    }
    
    public void setTomaGlucemia180(Integer tomaGlucemia180) {
        this.tomaGlucemia180 = tomaGlucemia180;
    }
    public String getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(String promedio) {
        this.promedio = promedio;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


