package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AnalisisLab generated by hbm2java
 */
public class AnalisisLab  implements java.io.Serializable {


     private int idAnalisis;
     private BitacoraLab bitacoraLab;
     private Muestra muestra;
     private TipoPrueba tipoPrueba;
     private Date fechaAnalisis;
     private Boolean estadoAna;
     private Set animals = new HashSet(0);
     private Set tratamientos = new HashSet(0);

    public AnalisisLab() {
    }

	
    public AnalisisLab(int idAnalisis, BitacoraLab bitacoraLab, Muestra muestra, TipoPrueba tipoPrueba) {
        this.idAnalisis = idAnalisis;
        this.bitacoraLab = bitacoraLab;
        this.muestra = muestra;
        this.tipoPrueba = tipoPrueba;
    }
    public AnalisisLab(int idAnalisis, BitacoraLab bitacoraLab, Muestra muestra, TipoPrueba tipoPrueba, Date fechaAnalisis, Boolean estadoAna, Set animals, Set tratamientos) {
       this.idAnalisis = idAnalisis;
       this.bitacoraLab = bitacoraLab;
       this.muestra = muestra;
       this.tipoPrueba = tipoPrueba;
       this.fechaAnalisis = fechaAnalisis;
       this.estadoAna = estadoAna;
       this.animals = animals;
       this.tratamientos = tratamientos;
    }
   
    public int getIdAnalisis() {
        return this.idAnalisis;
    }
    
    public void setIdAnalisis(int idAnalisis) {
        this.idAnalisis = idAnalisis;
    }
    public BitacoraLab getBitacoraLab() {
        return this.bitacoraLab;
    }
    
    public void setBitacoraLab(BitacoraLab bitacoraLab) {
        this.bitacoraLab = bitacoraLab;
    }
    public Muestra getMuestra() {
        return this.muestra;
    }
    
    public void setMuestra(Muestra muestra) {
        this.muestra = muestra;
    }
    public TipoPrueba getTipoPrueba() {
        return this.tipoPrueba;
    }
    
    public void setTipoPrueba(TipoPrueba tipoPrueba) {
        this.tipoPrueba = tipoPrueba;
    }
    public Date getFechaAnalisis() {
        return this.fechaAnalisis;
    }
    
    public void setFechaAnalisis(Date fechaAnalisis) {
        this.fechaAnalisis = fechaAnalisis;
    }
    public Boolean getEstadoAna() {
        return this.estadoAna;
    }
    
    public void setEstadoAna(Boolean estadoAna) {
        this.estadoAna = estadoAna;
    }
    public Set getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Set animals) {
        this.animals = animals;
    }
    public Set getTratamientos() {
        return this.tratamientos;
    }
    
    public void setTratamientos(Set tratamientos) {
        this.tratamientos = tratamientos;
    }




}


