package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1



/**
 * Animal generated by hbm2java
 */
public class Animal  implements java.io.Serializable {


     private int idAnimal;
     private AnalisisLab analisisLab;
     private CatalogoAnima catalogoAnima;
     private Boolean estadoAnimal;

    public Animal() {
    }

	
    public Animal(int idAnimal, AnalisisLab analisisLab, CatalogoAnima catalogoAnima) {
        this.idAnimal = idAnimal;
        this.analisisLab = analisisLab;
        this.catalogoAnima = catalogoAnima;
    }
    public Animal(int idAnimal, AnalisisLab analisisLab, CatalogoAnima catalogoAnima, Boolean estadoAnimal) {
       this.idAnimal = idAnimal;
       this.analisisLab = analisisLab;
       this.catalogoAnima = catalogoAnima;
       this.estadoAnimal = estadoAnimal;
    }
   
    public int getIdAnimal() {
        return this.idAnimal;
    }
    
    public void setIdAnimal(int idAnimal) {
        this.idAnimal = idAnimal;
    }
    public AnalisisLab getAnalisisLab() {
        return this.analisisLab;
    }
    
    public void setAnalisisLab(AnalisisLab analisisLab) {
        this.analisisLab = analisisLab;
    }
    public CatalogoAnima getCatalogoAnima() {
        return this.catalogoAnima;
    }
    
    public void setCatalogoAnima(CatalogoAnima catalogoAnima) {
        this.catalogoAnima = catalogoAnima;
    }
    public Boolean getEstadoAnimal() {
        return this.estadoAnimal;
    }
    
    public void setEstadoAnimal(Boolean estadoAnimal) {
        this.estadoAnimal = estadoAnimal;
    }




}


