package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cacerio generated by hbm2java
 */
public class Cacerio  implements java.io.Serializable {


     private int idCacerio;
     private ColoniaCanton coloniaCanton;
     private String nomCacerio;
     private Set ubicacions = new HashSet(0);

    public Cacerio() {
    }

	
    public Cacerio(int idCacerio, ColoniaCanton coloniaCanton, String nomCacerio) {
        this.idCacerio = idCacerio;
        this.coloniaCanton = coloniaCanton;
        this.nomCacerio = nomCacerio;
    }
    public Cacerio(int idCacerio, ColoniaCanton coloniaCanton, String nomCacerio, Set ubicacions) {
       this.idCacerio = idCacerio;
       this.coloniaCanton = coloniaCanton;
       this.nomCacerio = nomCacerio;
       this.ubicacions = ubicacions;
    }
   
    public int getIdCacerio() {
        return this.idCacerio;
    }
    
    public void setIdCacerio(int idCacerio) {
        this.idCacerio = idCacerio;
    }
    public ColoniaCanton getColoniaCanton() {
        return this.coloniaCanton;
    }
    
    public void setColoniaCanton(ColoniaCanton coloniaCanton) {
        this.coloniaCanton = coloniaCanton;
    }
    public String getNomCacerio() {
        return this.nomCacerio;
    }
    
    public void setNomCacerio(String nomCacerio) {
        this.nomCacerio = nomCacerio;
    }
    public Set getUbicacions() {
        return this.ubicacions;
    }
    
    public void setUbicacions(Set ubicacions) {
        this.ubicacions = ubicacions;
    }




}


