package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


/*import java.util.HashSet;
import java.util.Set;*/

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cargo generated by hbm2java
 */
/*public class Cargo  implements java.io.Serializable {


     private int idCargo;
     private String cargo;
     private Set usuarios = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public Cargo(int idCargo, String cargo, Set usuarios) {
       this.idCargo = idCargo;
       this.cargo = cargo;
       this.usuarios = usuarios;
    }
   
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}*/

public class Cargo  implements java.io.Serializable {


     private int idCargo;
     private String cargo;
     private Set usuarios = new HashSet(0);
     private String descripcion;
     private Date fechaCreacion;
     private Date fechaModifica;
     private Boolean activo;

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public Date getFechaModifica() {
        return fechaModifica;
    }

    public void setFechaModifica(Date fechaModifica) {
        this.fechaModifica = fechaModifica;
    }

    public Boolean getActivo() {
        return activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
     
     
     

    public Cargo() {
    }

	
    public Cargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public Cargo(int idCargo, String cargo, Set usuarios,String descripcion,Date fechaCreacion,Date fechaModifica,Boolean activo) {
       this.idCargo = idCargo;
       this.cargo = cargo;
       this.usuarios = usuarios;
       this.descripcion=descripcion;
       this.fechaCreacion=fechaCreacion;
       this.fechaModifica=fechaModifica;
       this.activo=activo;
    }
   
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


