package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CatalogoAnima generated by hbm2java
 */
public class CatalogoAnima  implements java.io.Serializable {


     private int idCatAnimal;
     private String nomAnimal;
     private boolean dispoAnimal;
     private Set animals = new HashSet(0);

    public CatalogoAnima() {
    }

	
    public CatalogoAnima(int idCatAnimal, String nomAnimal, boolean dispoAnimal) {
        this.idCatAnimal = idCatAnimal;
        this.nomAnimal = nomAnimal;
        this.dispoAnimal = dispoAnimal;
    }
    public CatalogoAnima(int idCatAnimal, String nomAnimal, boolean dispoAnimal, Set animals) {
       this.idCatAnimal = idCatAnimal;
       this.nomAnimal = nomAnimal;
       this.dispoAnimal = dispoAnimal;
       this.animals = animals;
    }
   
    public int getIdCatAnimal() {
        return this.idCatAnimal;
    }
    
    public void setIdCatAnimal(int idCatAnimal) {
        this.idCatAnimal = idCatAnimal;
    }
    public String getNomAnimal() {
        return this.nomAnimal;
    }
    
    public void setNomAnimal(String nomAnimal) {
        this.nomAnimal = nomAnimal;
    }
    public boolean isDispoAnimal() {
        return this.dispoAnimal;
    }
    
    public void setDispoAnimal(boolean dispoAnimal) {
        this.dispoAnimal = dispoAnimal;
    }
    public Set getAnimals() {
        return this.animals;
    }
    
    public void setAnimals(Set animals) {
        this.animals = animals;
    }




}


