package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private String codDepto;
     private String nomDepto;
     private Set municipios = new HashSet(0);

    public Departamento() {
    }

	
    public Departamento(String codDepto, String nomDepto) {
        this.codDepto = codDepto;
        this.nomDepto = nomDepto;
    }
    public Departamento(String codDepto, String nomDepto, Set municipios) {
       this.codDepto = codDepto;
       this.nomDepto = nomDepto;
       this.municipios = municipios;
    }
   
    public String getCodDepto() {
        return this.codDepto;
    }
    
    public void setCodDepto(String codDepto) {
        this.codDepto = codDepto;
    }
    public String getNomDepto() {
        return this.nomDepto;
    }
    
    public void setNomDepto(String nomDepto) {
        this.nomDepto = nomDepto;
    }
    public Set getMunicipios() {
        return this.municipios;
    }
    
    public void setMunicipios(Set municipios) {
        this.municipios = municipios;
    }




}


