package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta  implements java.io.Serializable {


     private int idEncuesta;
     private BitacoraCampo bitacoraCampo;
     private String nomEncuesta;
     private Set preguntas = new HashSet(0);
     private Set personas = new HashSet(0);

    public Encuesta() {
    }

	
    public Encuesta(int idEncuesta, BitacoraCampo bitacoraCampo) {
        this.idEncuesta = idEncuesta;
        this.bitacoraCampo = bitacoraCampo;
    }
    public Encuesta(int idEncuesta, BitacoraCampo bitacoraCampo, String nomEncuesta, Set preguntas, Set personas) {
       this.idEncuesta = idEncuesta;
       this.bitacoraCampo = bitacoraCampo;
       this.nomEncuesta = nomEncuesta;
       this.preguntas = preguntas;
       this.personas = personas;
    }
   
    public int getIdEncuesta() {
        return this.idEncuesta;
    }
    
    public void setIdEncuesta(int idEncuesta) {
        this.idEncuesta = idEncuesta;
    }
    public BitacoraCampo getBitacoraCampo() {
        return this.bitacoraCampo;
    }
    
    public void setBitacoraCampo(BitacoraCampo bitacoraCampo) {
        this.bitacoraCampo = bitacoraCampo;
    }
    public String getNomEncuesta() {
        return this.nomEncuesta;
    }
    
    public void setNomEncuesta(String nomEncuesta) {
        this.nomEncuesta = nomEncuesta;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


