package sv.ues.dominio;
// Generated Dec 12, 2019 11:36:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia  implements java.io.Serializable {


     private int id;
     private Orden orden;
     private String nombreFamilia;
     private Set vectors = new HashSet(0);

    public Familia() {
    }

	
    public Familia(int id, Orden orden, String nombreFamilia) {
        this.id = id;
        this.orden = orden;
        this.nombreFamilia = nombreFamilia;
    }
    public Familia(int id, Orden orden, String nombreFamilia, Set vectors) {
       this.id = id;
       this.orden = orden;
       this.nombreFamilia = nombreFamilia;
       this.vectors = vectors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public String getNombreFamilia() {
        return this.nombreFamilia;
    }
    
    public void setNombreFamilia(String nombreFamilia) {
        this.nombreFamilia = nombreFamilia;
    }
    public Set getVectors() {
        return this.vectors;
    }
    
    public void setVectors(Set vectors) {
        this.vectors = vectors;
    }




}


