package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InvVector generated by hbm2java
 */
public class InvVector  implements java.io.Serializable {


     private Integer idInvVector;
     private Investigacion investigacion;
     private Vector vector;
     private String tituloInv;
     private String descInvVector;
     private Set bitacoraCampos = new HashSet(0);
     private Set bitacoraLabs = new HashSet(0);
     private Date fechaRegistro;

    public InvVector() {
    }

	
    public InvVector(int idInvVector, Vector vector) {
        this.idInvVector = idInvVector;
        this.vector = vector;
    }
    public InvVector(Integer idInvVector, Investigacion investigacion, Vector vector, String tituloInv, String descInvVector,
            Set bitacoraCampos, Set bitacoraLabs, Date fechaRegistro) {
       this.idInvVector = idInvVector;
       this.fechaRegistro= fechaRegistro;
       this.investigacion = investigacion;
       this.vector = vector;
       this.tituloInv = tituloInv;
       this.descInvVector = descInvVector;
       this.bitacoraCampos = bitacoraCampos;
       this.bitacoraLabs = bitacoraLabs;
    }

    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    
    public Integer getIdInvVector() {
        return this.idInvVector;
    }
    
    public void setIdInvVector(Integer idInvVector) {
        this.idInvVector = idInvVector;
    }
    public Investigacion getInvestigacion() {
        return this.investigacion;
    }
    
    public void setInvestigacion(Investigacion investigacion) {
        this.investigacion = investigacion;
    }
    public Vector getVector() {
        return this.vector;
    }
    
    public void setVector(Vector vector) {
        this.vector = vector;
    }
    public String getTituloInv() {
        return this.tituloInv;
    }
    
    public void setTituloInv(String tituloInv) {
        this.tituloInv = tituloInv;
    }
    public String getDescInvVector() {
        return this.descInvVector;
    }
    
    public void setDescInvVector(String descInvVector) {
        this.descInvVector = descInvVector;
    }
    public Set getBitacoraCampos() {
        return this.bitacoraCampos;
    }
    
    public void setBitacoraCampos(Set bitacoraCampos) {
        this.bitacoraCampos = bitacoraCampos;
    }
    public Set getBitacoraLabs() {
        return this.bitacoraLabs;
    }
    
    public void setBitacoraLabs(Set bitacoraLabs) {
        this.bitacoraLabs = bitacoraLabs;
    }
    
    @Override
    public String toString() {
        return "InvVector [idInvVector=" + idInvVector + " ]";
    }

    @Override
    public boolean equals(Object object) {
          // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof InvVector)) {
            return false;
        }
        InvVector other = (InvVector) object;
        if ((this.idInvVector == null && other.idInvVector != null) || (this.idInvVector != null && !this.idInvVector.equals(other.idInvVector))) {
            return false;
        }
        return true;
    }


}


