package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private Integer codLaboratorio;
     private String nomLab;
     private String alias;
     private Set usuarios = new HashSet(0);
     private Set investigacions = new HashSet(0);

    public Laboratorio() {
    }

	
    public Laboratorio(Integer codLaboratorio, String nomLab) {
        this.codLaboratorio = codLaboratorio;
        this.nomLab = nomLab;
    }
    public Laboratorio(Integer codLaboratorio, String nomLab, String alias, Set usuarios, Set investigacions) {
       this.codLaboratorio = codLaboratorio;
       this.nomLab = nomLab;
       this.alias = alias;
       this.usuarios = usuarios;
       this.investigacions = investigacions;
    }
   
    public Integer getCodLaboratorio() {
        return this.codLaboratorio;
    }
    
    public void setCodLaboratorio(Integer codLaboratorio) {
        this.codLaboratorio = codLaboratorio;
    }
    public String getNomLab() {
        return this.nomLab;
    }
    
    public void setNomLab(String nomLab) {
        this.nomLab = nomLab;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getInvestigacions() {
        return this.investigacions;
    }
    
    public void setInvestigacions(Set investigacions) {
        this.investigacions = investigacions;
    }

    @Override
    public String toString() {
        return "Laboratorio[codLaboratorio=" + codLaboratorio + "]";
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 59 * hash + this.codLaboratorio;
        hash = 59 * hash + (this.nomLab != null ? this.nomLab.hashCode() : 0);
        hash = 59 * hash + (this.alias != null ? this.alias.hashCode() : 0);
        hash = 59 * hash + (this.usuarios != null ? this.usuarios.hashCode() : 0);
        hash = 59 * hash + (this.investigacions != null ? this.investigacions.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
          // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Laboratorio)) {
            return false;
        }
        Laboratorio other = (Laboratorio) object;
        if ((this.codLaboratorio == null && other.codLaboratorio != null) || (this.codLaboratorio != null && !this.codLaboratorio.equals(other.codLaboratorio))) {
            return false;
        }
        return true;
    }

    


}


