package sv.ues.dominio;
// Generated 21-nov-2019 13:01:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lote generated by hbm2java
 */
public class Lote  implements java.io.Serializable {


     private int idLote;
     private BitacoraLab bitacoraLab;
     private Lote lote;
     private Date fechaCreacion;
     private Date fechaModificacion;
     private Integer estatus;
     private String nombreLote;
     private Integer numMuestras;
     private Integer idVector;
     
     private Set mantenimientos = new HashSet(0);
     private Set lotes = new HashSet(0);
     private Set muestras = new HashSet(0);
     
private ColoniaCanton coloniaCanton;

    public Lote() {
    }

    
    public Lote(int idLote) {
        this.idLote = idLote;
    }
       
    public Lote(int idLote, BitacoraLab bitacoraLab, ColoniaCanton coloniaCanton, 
            Lote lote, Date fechaCreacion,
            Date fechaModificacion, Integer estatus,
            String nombreLote, Integer numMuestras, 
            Integer idVector, Set mantenimientos, Set lotes, Set muestras) {
       this.idLote = idLote;
       this.bitacoraLab = bitacoraLab;
       this.coloniaCanton = coloniaCanton;
       this.lote = lote;
       this.fechaCreacion = fechaCreacion;
       this.fechaModificacion = fechaModificacion;
       this.estatus = estatus;
       this.nombreLote = nombreLote;
       this.numMuestras = numMuestras;
       this.idVector = idVector;
       this.mantenimientos = mantenimientos;
       this.lotes = lotes;
       this.muestras = muestras;
    }
   
    public int getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(int idLote) {
        this.idLote = idLote;
    }
    public BitacoraLab getBitacoraLab() {
        return this.bitacoraLab;
    }
    
    public void setBitacoraLab(BitacoraLab bitacoraLab) {
        this.bitacoraLab = bitacoraLab;
    }
    public Lote getLote() {
        return this.lote;
    }
    
    public void setLote(Lote lote) {
        this.lote = lote;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }
    public Integer getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Integer estatus) {
        this.estatus = estatus;
    }
    public String getNombreLote() {
        return this.nombreLote;
    }
    
    public void setNombreLote(String nombreLote) {
        this.nombreLote = nombreLote;
    }
    public Integer getNumMuestras() {
        return this.numMuestras;
    }
    
    public void setNumMuestras(Integer numMuestras) {
        this.numMuestras = numMuestras;
    }
    public Integer getIdVector() {
        return this.idVector;
    }
    
    public void setIdVector(Integer idVector) {
        this.idVector = idVector;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }
    public Set getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Set lotes) {
        this.lotes = lotes;
    }
    public Set getMuestras() {
        return this.muestras;
    }
    
    public void setMuestras(Set muestras) {
        this.muestras = muestras;
    }

    public ColoniaCanton getColoniaCanton() {
        return coloniaCanton;
    }

    public void setColoniaCanton(ColoniaCanton coloniaCanton) {
        this.coloniaCanton = coloniaCanton;
    }




}


