package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private int idMenu;
     private Menu menu;
     private String nomMenu;
     private String ruta;
     private String icono;
     private Integer orden;
     private Boolean disponible;
     private Set menus = new HashSet(0);
     private Set permisos = new HashSet(0);
     private Set rols = new HashSet(0);

    public Menu() {
    }

	
    public Menu(int idMenu, String nomMenu) {
        this.idMenu = idMenu;
        this.nomMenu = nomMenu;
    }
    public Menu(int idMenu, Menu menu, String nomMenu, String ruta, String icono, Integer orden, Boolean disponible, Set menus, Set permisos) {
       this.idMenu = idMenu;
       this.menu = menu;
       this.nomMenu = nomMenu;
       this.ruta = ruta;
       this.icono = icono;
       this.orden = orden;
       this.disponible = disponible;
       this.menus = menus;
       this.permisos = permisos;
    }
   
    public int getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(int idMenu) {
        this.idMenu = idMenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getNomMenu() {
        return this.nomMenu;
    }
    
    public void setNomMenu(String nomMenu) {
        this.nomMenu = nomMenu;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }
    public Boolean getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(Boolean disponible) {
        this.disponible = disponible;
    }
    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }
    public Set getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Set permisos) {
        this.permisos = permisos;
    }

    public Set getRols() {
        return rols;
    }

    public void setRols(Set rols) {
        this.rols = rols;
    }


}


