package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Municipio generated by hbm2java
 */
public class Municipio  implements java.io.Serializable {


     private String codMunicipio;
     private Departamento departamento;
     private String nomMunicipio;
     private Set coloniaCantons = new HashSet(0);

    public Municipio() {
    }

	
    public Municipio(String codMunicipio, Departamento departamento, String nomMunicipio) {
        this.codMunicipio = codMunicipio;
        this.departamento = departamento;
        this.nomMunicipio = nomMunicipio;
    }
    public Municipio(String codMunicipio, Departamento departamento, String nomMunicipio, Set coloniaCantons) {
       this.codMunicipio = codMunicipio;
       this.departamento = departamento;
       this.nomMunicipio = nomMunicipio;
       this.coloniaCantons = coloniaCantons;
    }
   
    public String getCodMunicipio() {
        return this.codMunicipio;
    }
    
    public void setCodMunicipio(String codMunicipio) {
        this.codMunicipio = codMunicipio;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNomMunicipio() {
        return this.nomMunicipio;
    }
    
    public void setNomMunicipio(String nomMunicipio) {
        this.nomMunicipio = nomMunicipio;
    }
    public Set getColoniaCantons() {
        return this.coloniaCantons;
    }
    
    public void setColoniaCantons(Set coloniaCantons) {
        this.coloniaCantons = coloniaCantons;
    }




}


