package sv.ues.dominio;
// Generated Dec 12, 2019 11:36:39 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Orden generated by hbm2java
 */
public class Orden  implements java.io.Serializable {


     private int id;
     private String nombreOrden;
     private Set familias = new HashSet(0);

    public Orden() {
    }

	
    public Orden(int id, String nombreOrden) {
        this.id = id;
        this.nombreOrden = nombreOrden;
    }
    public Orden(int id, String nombreOrden, Set familias) {
       this.id = id;
       this.nombreOrden = nombreOrden;
       this.familias = familias;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombreOrden() {
        return this.nombreOrden;
    }
    
    public void setNombreOrden(String nombreOrden) {
        this.nombreOrden = nombreOrden;
    }
    public Set getFamilias() {
        return this.familias;
    }
    
    public void setFamilias(Set familias) {
        this.familias = familias;
    }




}


