package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * PerfilInv generated by hbm2java
 */
public class PerfilInv  implements java.io.Serializable {


     private int idPerfil;
     private Investigacion investigacion;
     private PerfilInv perfilInv;
     private String antecedente;
     private String justificacion;
     private String planteamiento;
     private String objGeneral;
     private String objEspecifico;
     private String metodologia;
     private String descResul;
     private BigDecimal presupuesto;
     private Integer numeroPersona;
     private PerfilInv perfilInvs ;
     private Set documentos = new HashSet(0);

    public PerfilInv() {
    }

	
    public PerfilInv(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public PerfilInv(int idPerfil, Investigacion investigacion, PerfilInv perfilInv, String antecedente, String justificacion, String planteamiento, String objGeneral, String objEspecifico, String metodologia, String descResul, BigDecimal presupuesto, Integer numeroPersona, PerfilInv perfilInvs, Set documentos) {
       this.idPerfil = idPerfil;
       this.investigacion = investigacion;
       this.perfilInv = perfilInv;
       this.antecedente = antecedente;
       this.justificacion = justificacion;
       this.planteamiento = planteamiento;
       this.objGeneral = objGeneral;
       this.objEspecifico = objEspecifico;
       this.metodologia = metodologia;
       this.descResul = descResul;
       this.presupuesto = presupuesto;
       this.numeroPersona = numeroPersona;
       this.perfilInvs = perfilInvs;
       this.documentos = documentos;
    }
   
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }
    public Investigacion getInvestigacion() {
        return this.investigacion;
    }
    
    public void setInvestigacion(Investigacion investigacion) {
        this.investigacion = investigacion;
    }
    public PerfilInv getPerfilInv() {
        return this.perfilInv;
    }
    
    public void setPerfilInv(PerfilInv perfilInv) {
        this.perfilInv = perfilInv;
    }
    public String getAntecedente() {
        return this.antecedente;
    }
    
    public void setAntecedente(String antecedente) {
        this.antecedente = antecedente;
    }
    public String getJustificacion() {
        return this.justificacion;
    }
    
    public void setJustificacion(String justificacion) {
        this.justificacion = justificacion;
    }
    public String getPlanteamiento() {
        return this.planteamiento;
    }
    
    public void setPlanteamiento(String planteamiento) {
        this.planteamiento = planteamiento;
    }
    public String getObjGeneral() {
        return this.objGeneral;
    }
    
    public void setObjGeneral(String objGeneral) {
        this.objGeneral = objGeneral;
    }
    public String getObjEspecifico() {
        return this.objEspecifico;
    }
    
    public void setObjEspecifico(String objEspecifico) {
        this.objEspecifico = objEspecifico;
    }
    public String getMetodologia() {
        return this.metodologia;
    }
    
    public void setMetodologia(String metodologia) {
        this.metodologia = metodologia;
    }
    public String getDescResul() {
        return this.descResul;
    }
    
    public void setDescResul(String descResul) {
        this.descResul = descResul;
    }
    public BigDecimal getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(BigDecimal presupuesto) {
        this.presupuesto = presupuesto;
    }
    public Integer getNumeroPersona() {
        return this.numeroPersona;
    }
    
    public void setNumeroPersona(Integer numeroPersona) {
        this.numeroPersona = numeroPersona;
    }
    public PerfilInv getPerfilInvs() {
        return this.perfilInvs;
    }
    
    public void setPerfilInvs(PerfilInv perfilInvs) {
        this.perfilInvs = perfilInvs;
    }
    public Set getDocumentos() {
        return this.documentos;
    }
    
    public void setDocumentos(Set documentos) {
        this.documentos = documentos;
    }


    @Override
    public String toString() {
        return "PerfilInv [idPerfil=" + idPerfil + " ]";
    }


}


