package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int idPregunta;
     private Encuesta encuesta;
     private String descPregunta;
     private Set respuestas = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int idPregunta, Encuesta encuesta, String descPregunta) {
        this.idPregunta = idPregunta;
        this.encuesta = encuesta;
        this.descPregunta = descPregunta;
    }
    public Pregunta(int idPregunta, Encuesta encuesta, String descPregunta, Set respuestas) {
       this.idPregunta = idPregunta;
       this.encuesta = encuesta;
       this.descPregunta = descPregunta;
       this.respuestas = respuestas;
    }
   
    public int getIdPregunta() {
        return this.idPregunta;
    }
    
    public void setIdPregunta(int idPregunta) {
        this.idPregunta = idPregunta;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public String getDescPregunta() {
        return this.descPregunta;
    }
    
    public void setDescPregunta(String descPregunta) {
        this.descPregunta = descPregunta;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


