package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Preservante generated by hbm2java
 */
public class Preservante  implements java.io.Serializable {


     private int idPreservante;
     private String nomPreservante;
     private String descPreservante;
     private Set mantenimientos = new HashSet(0);

    public Preservante() {
    }

	
    public Preservante(int idPreservante, String nomPreservante, String descPreservante) {
        this.idPreservante = idPreservante;
        this.nomPreservante = nomPreservante;
        this.descPreservante = descPreservante;
    }
    public Preservante(int idPreservante, String nomPreservante, String descPreservante, Set mantenimientos) {
       this.idPreservante = idPreservante;
       this.nomPreservante = nomPreservante;
       this.descPreservante = descPreservante;
       this.mantenimientos = mantenimientos;
    }
   
    public int getIdPreservante() {
        return this.idPreservante;
    }
    
    public void setIdPreservante(int idPreservante) {
        this.idPreservante = idPreservante;
    }
    public String getNomPreservante() {
        return this.nomPreservante;
    }
    
    public void setNomPreservante(String nomPreservante) {
        this.nomPreservante = nomPreservante;
    }
    public String getDescPreservante() {
        return this.descPreservante;
    }
    
    public void setDescPreservante(String descPreservante) {
        this.descPreservante = descPreservante;
    }
    public Set getMantenimientos() {
        return this.mantenimientos;
    }
    
    public void setMantenimientos(Set mantenimientos) {
        this.mantenimientos = mantenimientos;
    }




}


