package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private int idRespuesta;
     private Pregunta pregunta;
     private TipoRespuesta tipoRespuesta;
     private String opcionRespuesta;
     private Set detalles = new HashSet(0);

    public Respuesta() {
    }

	
    public Respuesta(int idRespuesta, Pregunta pregunta, TipoRespuesta tipoRespuesta, String opcionRespuesta) {
        this.idRespuesta = idRespuesta;
        this.pregunta = pregunta;
        this.tipoRespuesta = tipoRespuesta;
        this.opcionRespuesta = opcionRespuesta;
    }
    public Respuesta(int idRespuesta, Pregunta pregunta, TipoRespuesta tipoRespuesta, String opcionRespuesta, Set detalles) {
       this.idRespuesta = idRespuesta;
       this.pregunta = pregunta;
       this.tipoRespuesta = tipoRespuesta;
       this.opcionRespuesta = opcionRespuesta;
       this.detalles = detalles;
    }
   
    public int getIdRespuesta() {
        return this.idRespuesta;
    }
    
    public void setIdRespuesta(int idRespuesta) {
        this.idRespuesta = idRespuesta;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public TipoRespuesta getTipoRespuesta() {
        return this.tipoRespuesta;
    }
    
    public void setTipoRespuesta(TipoRespuesta tipoRespuesta) {
        this.tipoRespuesta = tipoRespuesta;
    }
    public String getOpcionRespuesta() {
        return this.opcionRespuesta;
    }
    
    public void setOpcionRespuesta(String opcionRespuesta) {
        this.opcionRespuesta = opcionRespuesta;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }




}


