package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoRespuesta generated by hbm2java
 */
public class TipoRespuesta  implements java.io.Serializable {


     private int idTipoResp;
     private String detalleResp;
     private Set respuestas = new HashSet(0);

    public TipoRespuesta() {
    }

	
    public TipoRespuesta(int idTipoResp, String detalleResp) {
        this.idTipoResp = idTipoResp;
        this.detalleResp = detalleResp;
    }
    public TipoRespuesta(int idTipoResp, String detalleResp, Set respuestas) {
       this.idTipoResp = idTipoResp;
       this.detalleResp = detalleResp;
       this.respuestas = respuestas;
    }
   
    public int getIdTipoResp() {
        return this.idTipoResp;
    }
    
    public void setIdTipoResp(int idTipoResp) {
        this.idTipoResp = idTipoResp;
    }
    public String getDetalleResp() {
        return this.detalleResp;
    }
    
    public void setDetalleResp(String detalleResp) {
        this.detalleResp = detalleResp;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


