package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoPrueba generated by hbm2java
 */
public class TipoPrueba  implements java.io.Serializable {


     private int idTipoPrueba;
     private String nomPrueba;
     private Boolean estadoDisp;
     private Set analisisLabs = new HashSet(0);

    public TipoPrueba() {
    }

	
    public TipoPrueba(int idTipoPrueba, String nomPrueba) {
        this.idTipoPrueba = idTipoPrueba;
        this.nomPrueba = nomPrueba;
    }
    public TipoPrueba(int idTipoPrueba, String nomPrueba, Boolean estadoDisp, Set analisisLabs) {
       this.idTipoPrueba = idTipoPrueba;
       this.nomPrueba = nomPrueba;
       this.estadoDisp = estadoDisp;
       this.analisisLabs = analisisLabs;
    }
   
    public int getIdTipoPrueba() {
        return this.idTipoPrueba;
    }
    
    public void setIdTipoPrueba(int idTipoPrueba) {
        this.idTipoPrueba = idTipoPrueba;
    }
    public String getNomPrueba() {
        return this.nomPrueba;
    }
    
    public void setNomPrueba(String nomPrueba) {
        this.nomPrueba = nomPrueba;
    }
    public Boolean getEstadoDisp() {
        return this.estadoDisp;
    }
    
    public void setEstadoDisp(Boolean estadoDisp) {
        this.estadoDisp = estadoDisp;
    }
    public Set getAnalisisLabs() {
        return this.analisisLabs;
    }
    
    public void setAnalisisLabs(Set analisisLabs) {
        this.analisisLabs = analisisLabs;
    }




}


