package sv.ues.dominio;
// Generated 10-28-2019 09:05:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tratamiento generated by hbm2java
 */
public class Tratamiento  implements java.io.Serializable {


     private int idTratamiento;
     private AnalisisLab analisisLab;
     private String descTratamiento;
     private String resultadoTratamiento;
     private Date fechaTratamiento;

    public Tratamiento() {
    }

	
    public Tratamiento(int idTratamiento, AnalisisLab analisisLab, String descTratamiento) {
        this.idTratamiento = idTratamiento;
        this.analisisLab = analisisLab;
        this.descTratamiento = descTratamiento;
    }
    public Tratamiento(int idTratamiento, AnalisisLab analisisLab, String descTratamiento, String resultadoTratamiento, Date fechaTratamiento) {
       this.idTratamiento = idTratamiento;
       this.analisisLab = analisisLab;
       this.descTratamiento = descTratamiento;
       this.resultadoTratamiento = resultadoTratamiento;
       this.fechaTratamiento = fechaTratamiento;
    }
   
    public int getIdTratamiento() {
        return this.idTratamiento;
    }
    
    public void setIdTratamiento(int idTratamiento) {
        this.idTratamiento = idTratamiento;
    }
    public AnalisisLab getAnalisisLab() {
        return this.analisisLab;
    }
    
    public void setAnalisisLab(AnalisisLab analisisLab) {
        this.analisisLab = analisisLab;
    }
    public String getDescTratamiento() {
        return this.descTratamiento;
    }
    
    public void setDescTratamiento(String descTratamiento) {
        this.descTratamiento = descTratamiento;
    }
    public String getResultadoTratamiento() {
        return this.resultadoTratamiento;
    }
    
    public void setResultadoTratamiento(String resultadoTratamiento) {
        this.resultadoTratamiento = resultadoTratamiento;
    }
    public Date getFechaTratamiento() {
        return this.fechaTratamiento;
    }
    
    public void setFechaTratamiento(Date fechaTratamiento) {
        this.fechaTratamiento = fechaTratamiento;
    }




}


