package sv.ues.dominio;
// Generated 08-22-2019 08:34:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Cargo cargo;
     private String nomUsuario;
     //private String email;
     private String clave;
     private boolean activo;
     private Set personas = new HashSet(0);
     private Set laboratorios = new HashSet(0);
     private Set rols = new HashSet(0);
     
     
    private Date fechaRegistro;
    private Date fechaUltimaModificacion;
    private String hash;

    public Usuario() {
    }

	
    public Usuario(int idUsuario, Cargo cargo, String nomUsuario, /*String email,*/ String clave, boolean activo) {
        this.idUsuario = idUsuario;
        this.cargo = cargo;
        this.nomUsuario = nomUsuario;
        //this.email = email;
        this.clave = clave;
        this.activo = activo;
    }
    public Usuario(int idUsuario, Cargo cargo, String nomUsuario, /*String email,*/ String clave, boolean activo, Set personas, Set laboratorios, Set rols) {
       this.idUsuario = idUsuario;
       this.cargo = cargo;
       this.nomUsuario = nomUsuario;
       //this.email = email;
       this.clave = clave;
       this.activo = activo;
       this.personas = personas;
       this.laboratorios = laboratorios;
       this.rols = rols;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }
    public String getNomUsuario() {
        return this.nomUsuario;
    }
    
    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }
    /*public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }*/
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }
    public Set getLaboratorios() {
        return this.laboratorios;
    }
    
    public void setLaboratorios(Set laboratorios) {
        this.laboratorios = laboratorios;
    }
    public Set getRols() {
        return this.rols;
    }
    
    public void setRols(Set rols) {
        
        this.rols = rols;
    }

    public Date getFechaRegistro() {
        return fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Date getFechaUltimaModificacion() {
        return fechaUltimaModificacion;
    }

    public void setFechaUltimaModificacion(Date fechaUltimaModificacion) {
        this.fechaUltimaModificacion = fechaUltimaModificacion;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }




}


